name: gops

channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults

dependencies:
  - python=3.8
  - pytorch>=1.13.0
  - numpy>1.16.0
  - ray-default>=1.0.0
  - pandas
  - tensorboard>=2.5.0
  - matplotlib
  - seaborn
  - scipy
  - cyipopt
  - llvm-openmp<16
  - pip
  - pip:
    - gym==0.23.1
    - gymnasium
    - box2d
    - pygame
    - pyglet
    - slxpy
    - openpyxl
    - intel-openmp
    - pytest