__version__ = "1.0.0"

model = "lqs2a1"

[simulink]
    solver = "FixedStepAuto"
    absolute_time = false
    integer_code = false
    non_finite = false
    complex = false
    continuous_time = true
    variable_size_signal = false
    non_inlined_sfcn = false

[cpp]
    class_name = "lqs2a1"
    namespace = ""


[info]
    description = "<auto>"
    version = "<auto>"
    author = "<auto>"
    license = "<no-license>"
